# name: 'rakis'
# url: 'https://github.com/sample-usr/rakis.nvim'
# preferred_background: 100c0a

fish_color_normal c1a386
fish_color_command 33c1b3
fish_color_param a079d8
fish_color_keyword 84bc5c
fish_color_quote f4af25
fish_color_redirection 5899e4
fish_color_end a079d8
fish_color_comment 997b66
fish_color_error e25054
fish_color_gray 997b66
fish_color_selection --background=412b25
fish_color_search_match --background=412b25
fish_color_option f4af25
fish_color_operator 5899e4
fish_color_escape a079d8
fish_color_autosuggestion 997b66
fish_color_cancel e25054
fish_color_cwd f96f1f
fish_color_user b89be2
fish_color_host 84bc5c
fish_color_host_remote f4af25
fish_color_status e25054
fish_pager_color_progress 997b66
fish_pager_color_prefix 5899e4
fish_pager_color_completion c1a386
fish_pager_color_description 997b66
