# rakis-default theme for ghostty
palette = 0=#100c0a
palette = 1=#e25054
palette = 2=#84bc5c
palette = 3=#f4af25
palette = 4=#5899e4
palette = 5=#a079d8
palette = 6=#33c1b3
palette = 7=#c1a386
palette = 8=#997b66
palette = 9=#e97c7f
palette = 10=#a3cd85
palette = 11=#f7c35c
palette = 12=#82b3eb
palette = 13=#b89be2
palette = 14=#66d1c6
palette = 15=#d1baa4

background = #100c0a
foreground = #c1a386
cursor-color = #c1a386
cursor-text = #100c0a
selection-background = #412b25
selection-foreground = #c1a386
