# rakis-${variant} theme for ghostty
palette = 0=#f2e7ce
palette = 1=#8c1616
palette = 2=#3b543a
palette = 3=#7a5a09
palette = 4=#13317a
palette = 5=#652951
palette = 6=#2c6376
palette = 7=#262626
palette = 8=#dac4ae
palette = 9=#c71818
palette = 10=#418c3f
palette = 11=#ba8707
palette = 12=#1643b5
palette = 13=#963576
palette = 14=#30809b
palette = 15=#262626

background = #f2e7ce
foreground = #262626
cursor-color = #262626
selection-background = #dac4ae
selection-foreground = #262626
