# rakis-default theme for tmux
# Source in your tmux.conf:
#   source-file path/to/rakis.conf
set -g mode-style "fg=#100c0a,bg=#f4af25"
set -g message-style "fg=#c1a386,bg=#2d201b"
set -g message-command-style "fg=#c1a386,bg=#2d201b"

set -g pane-border-style "fg=#2d201b"
set -g pane-active-border-style "fg=#f96f1f"

set -g status-style "fg=#997b66,bg=#1c1512"
set -g status-left "#[fg=#100c0a,bg=#f96f1f,bold] #S "
set -g status-right "#[fg=#997b66,bg=#1c1512] %Y-%m-%d %H:%M #[fg=#100c0a,bg=#f96f1f,bold] #h "

set -g window-status-format "#[fg=#997b66,bg=#1c1512] #I #W "
set -g window-status-current-format "#[fg=#c1a386,bg=#2d201b,bold] #I #W "
set -g window-status-separator ""
set -g window-status-activity-style "fg=#f4af25,bg=#1c1512"
set -g window-status-bell-style "fg=#e25054,bg=#1c1512"

set -g clock-mode-colour "#f96f1f"
set -g copy-mode-match-style "fg=#100c0a,bg=#997b66"
set -g copy-mode-current-match-style "fg=#100c0a,bg=#f4af25"
