# rakis-light theme for kitty
foreground #4c3424
background #f2e7cf
selection_foreground #4c3424
selection_background #d2baa2

cursor #4c3424
cursor_text_color #f2e7cf

url_color #1c589c

active_border_color #a3420a
inactive_border_color #dccab2
bell_border_color #8b5e04

active_tab_foreground #4c3424
active_tab_background #dccab2
inactive_tab_foreground #6e5749
inactive_tab_background #e7d9c0
tab_bar_background #f2e7cf

color0 #f2e7cf
color8 #837167

color1 #aa181d
color9 #bf5256

color2 #416b24
color10 #71905b

color3 #8b5e04
color11 #a88643

color4 #1c589c
color12 #5582b5

color5 #6236a1
color13 #8968b9

color6 #166961
color14 #508f89

color7 #4c3424
color15 #79675b
