# rakis-default theme for kitty
foreground #c1a386
background #100c0a
selection_foreground #c1a386
selection_background #412b25

cursor #c1a386
cursor_text_color #100c0a

url_color #5899e4

active_border_color #f96f1f
inactive_border_color #2d201b
bell_border_color #f4af25

active_tab_foreground #c1a386
active_tab_background #2d201b
inactive_tab_foreground #997b66
inactive_tab_background #1c1512
tab_bar_background #100c0a

color0 #100c0a
color8 #756157

color1 #e25054
color9 #e97c7f

color2 #84bc5c
color10 #a3cd85

color3 #f4af25
color11 #f7c35c

color4 #5899e4
color12 #82b3eb

color5 #a079d8
color13 #b89be2

color6 #33c1b3
color14 #66d1c6

color7 #c1a386
color15 #d1baa4
